### ISSUE TITLE
feat(make uniform to "@aws-amplify/auth")

### ISSUE THREAD

**Issue by morrys** [aws/amazon-cognito-auth-js#197]
in this pull request (https://github.com/aws-amplify/amplify-js/pull/3005) the flows for Cognito Hosted UI endpoints have been simplified and new features added.
Why was it chosen to remove the dependency on this library instead of evolving it? Is it a repository that will be deprecated?

Thanks

**Comment by undefobj** [comment]
@morrys we are trying to reduce dependencies to keep bundle size small as well as ensure that we can add features quickly (such as the PKCE support that was built in). Additionally this reduces surface area for 3rd party security concerns. Most likely we will deprecate that other library in the future as well so that customers don't need to keep track of multiple libraries.
