### ISSUE TITLE
how to set state parameter in the callback URL? 

### ISSUE THREAD

**Issue by goldenbearkin** [aws/amazon-cognito-auth-js#44]
I have a SPA and would like to pass back the route information so that user can redirect to the route where they intend to access before undergo authentication.

I found from the aws documentation http://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html saying i can pass the state value back to the client:

and i tried this but didn't work
```js
{
  ClientId: '*************************',
  AppWebDomain: '***********.auth.ap-northeast-1.amazoncognito.com',
  TokenScopesArray: ['email openid profile'],
  RedirectUriSignIn: `https://*****/cognitocallback?STATE=dashboard`,
  RedirectUriSignOut: `https://*****`
}
````
i can find auth.getSession() the only api to sign-in user. Please suggest how to do it for this library? Many thanks

*I am sorry that i asked the same question before but got closed immediately.

**Comment by jonasao** [comment]
Any feedback on this one from the AWS Cognito team would be much appreciated!

**Comment by yuntuowang** [comment]
@jonasao is correct.

**Comment by yuntuowang** [comment]
What @jonasao mentioned is correct, apart from that, if @goldenbearkin  have a specific use case and need to set a "state" parameter to store some info when redirecting between different pages, could you describe your use case in more details? We can see if we can help from our side.

**Comment by davepacifico** [comment]
So the primary use-case is as @goldenbearkin said - to redirect the user back to the original url they requested. Basically, you can do something like Base64 encode a string which includes both a nonce and the original url the user requested (say /posts/5) and then when authentication succeeds and the built-in Cognito login UI redirects to your static redirect url (perhaps /login), you can decode the state parameter and redirect the user to /posts/5 as they originally requested. 

From my perspective that is a pretty critical user experience. It's what I was doing when I was using amazon-cognito-identity-js directly, but I have found this library to be very useful other than that one (relatively major) issue. I'm hoping I can manage to work around it rather than bail on the library entirely. Suggestions are welcome.

**Comment by mymattcarroll** [comment]
I would suggest storing the url your user is attempting to go to in local storage before directing to the hosted login screen. After login and redirection back to generic callback screen, pull the desired url back out of local storage and redirect to it.
